# Generated by Django 4.0.4 on 2022-06-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
