# Generated by Django 4.0.4 on 2022-06-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_bio_user_address_user_city_user_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(default='123'),
        ),
    ]
