# Generated by Django 4.0.4 on 2022-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/images/account/default_profile.png', null=True, upload_to='profile_img'),
        ),
    ]
