# Generated by Django 4.0.4 on 2022-06-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterData',
            new_name='SiteData',
        ),
    ]
