# Generated by Django 4.0.4 on 2022-06-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_color_color_img_alter_product_product_img'),
        ('home', '0002_rename_footerdata_sitedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=160)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
