# Generated by Django 4.0.4 on 2023-08-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homesectiontwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSectionTwo',
        ),
    ]
