# Generated by Django 4.0.4 on 2024-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_patreonimage_delete_homesectionone_sitedata_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='brand',
            new_name='home_logo',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='footer_large_text1',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='footer_large_text2',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='home_banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='home_banner'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='home_heading',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='home_paragraph',
            field=models.CharField(default='', max_length=160),
        ),
    ]
