# Generated by Django 5.0.1 on 2024-04-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
