# Generated by Django 4.0.4 on 2022-07-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_placeorder_address_placeorder_city_placeorder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='address',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='city',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='name',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='state',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
