# Generated by Django 4.0.4 on 2022-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_placeorder_address_alter_placeorder_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='phone',
            field=models.IntegerField(default=123456789, null=True),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='zip_code',
            field=models.IntegerField(default='123', null=True),
        ),
    ]
