# Generated by Django 4.0.4 on 2022-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_placeorder_phone_alter_placeorder_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='color',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='size',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
