# Generated by Django 4.0.4 on 2022-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_placeorder_color_placeorder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='order_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
