# Generated by Django 4.0.4 on 2022-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_placeorder_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='order_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
