# Generated by Django 4.2.6 on 2024-01-06 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_city_product_complete_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0014_alter_placeorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_point', models.CharField(max_length=255)),
                ('car_location', models.CharField(max_length=255)),
                ('rent_days', models.PositiveIntegerField(default=1)),
                ('pickup_time', models.TimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_name', models.CharField(default='None', max_length=100, null=True)),
                ('user_state', models.CharField(default='None', max_length=100, null=True)),
                ('user_address', models.CharField(default='None', max_length=200, null=True)),
                ('user_city', models.CharField(default='None', max_length=100, null=True)),
                ('user_zip_code', models.IntegerField(default='123', null=True)),
                ('user_phone', models.IntegerField(default=123456789, null=True)),
                ('order_price', models.FloatField(default=0, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=150)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
