# Generated by Django 4.2.6 on 2024-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_date',
            field=models.DateField(null=True),
        ),
    ]
