# Generated by Django 4.2.6 on 2024-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_booking_dropoff_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Active', 'Active')], default='Processing', max_length=150),
        ),
    ]
