# Generated by Django 4.2.6 on 2024-01-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_booking_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='car_location',
            new_name='seller_car_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_state',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_zip_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Active', 'Active'), ('Done', 'Done')], default='Processing', max_length=150),
        ),
    ]
