# Generated by Django 4.2.6 on 2024-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_rename_user_city_booking_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('DropOff', 'DropOff'), ('Late', 'Late'), ('Cancel', 'Cancel')], default='Pending', max_length=150),
        ),
    ]
