# Generated by Django 4.2.6 on 2024-01-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='rent_days',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='dropoff_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='dropoff_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_point',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='seller_car_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_address',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_name',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_phone',
            field=models.IntegerField(default=123456789, null=True),
        ),
        migrations.DeleteModel(
            name='PlaceOrder',
        ),
    ]
