# Generated by Django 5.0.1 on 2024-03-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_rename_order_price_booking_user_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
