# Generated by Django 4.0.4 on 2022-06-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('color_img', models.ImageField(upload_to='images/product/color')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('product_img', models.ImageField(upload_to='images/product')),
                ('how_use', models.CharField(max_length=500)),
                ('pro_tips', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=300)),
                ('heighlights', models.TextField(default='\n    <strong>What is it? </strong>\n    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis vero voluptas ducimus inventore enim. Voluptas ipsam modi aliquid dicta voluptatem sit rem praesentium repellat corrupti, officia ducimus quos saepe molestias.</p>\n    <br/>\n    <strong>What makes it special? </strong>\n    <ul>\n        <li>Olive Oil Glossing Polish (6oz) enhances your hair for incredible shine and restores moisture to hair </li>\n        <li>Helps to eliminate frizz and fly-always and resist humidity for longer lasting style </li>\n        <li>Helps to leave hair healthy and more manageable </li>\n    </ul>')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('color', models.ManyToManyField(to='products.color')),
                ('size', models.ManyToManyField(to='products.size')),
            ],
        ),
    ]
