# Generated by Django 4.0.4 on 2022-06-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_product_permalink_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Permalink',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
