# Generated by Django 4.0.4 on 2022-06-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_color_color_img_alter_product_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Permalink',
            new_name='permalink',
        ),
    ]
