# Generated by Django 4.0.4 on 2022-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.FloatField(default=0),
        ),
    ]
