# Generated by Django 4.2.6 on 2024-01-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
    ]
