# Generated by Django 4.2.6 on 2024-01-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seats',
            field=models.FloatField(default=0),
        ),
    ]
