# Generated by Django 4.2.6 on 2024-01-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='how_use',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='instructions',
            field=models.CharField(default='', max_length=300),
        ),
    ]
