# Generated by Django 4.0.4 on 2024-02-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping_price',
            new_name='total_tax',
        ),
    ]
