# Generated by Django 4.0.4 on 2024-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_rename_shipping_price_product_total_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
