# Generated by Django 5.0.1 on 2024-03-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_customdiscount_delete_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='damage_coverage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='supplemental_liability_coverage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='use_own_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
