# Generated by Django 5.0.1 on 2024-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_available_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaibleTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_timing',
        ),
        migrations.AddField(
            model_name='product',
            name='available_timing',
            field=models.ManyToManyField(null=True, to='products.avaibletiming'),
        ),
    ]
