# Generated by Django 5.0.1 on 2024-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_avaibletiming_remove_product_available_timing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaibletiming',
            name='time',
        ),
        migrations.AddField(
            model_name='avaibletiming',
            name='Time',
            field=models.CharField(default='', max_length=160, unique=True),
        ),
    ]
