# Generated by Django 5.0.1 on 2024-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_avaibletiming_time_avaibletiming_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=160, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_locations',
            field=models.ManyToManyField(null=True, to='products.pickuplocation'),
        ),
    ]
