# Generated by Django 5.0.1 on 2024-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_pickuplocation_product_pickup_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_img')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='product_thumb',
        ),
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(null=True, to='products.productimages'),
        ),
    ]
