# Generated by Django 5.0.1 on 2024-04-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_productimages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customdiscount',
            old_name='discount_price',
            new_name='discount_price_percentage',
        ),
    ]
