# Generated by Django 5.0.1 on 2024-04-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_rename_discount_price_customdiscount_discount_price_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='rent_per_day_price',
        ),
    ]
