# Generated by Django 5.0.1 on 2024-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_rename_discounted_price_product_rent_per_day_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='damage_coverage',
            new_name='insurance_amount_per_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplemental_liability_coverage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='use_own_insurance',
        ),
        migrations.AddField(
            model_name='product',
            name='insurance_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
