# Generated by Django 5.0.1 on 2024-06-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_rename_damage_coverage_product_insurance_amount_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_deposite_percentage',
            field=models.FloatField(default=0),
        ),
    ]
