# Generated by Django 5.0.1 on 2024-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_product_custom_deposite_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='seven_day_book_discount',
            field=models.FloatField(default=0),
        ),
    ]
