# Generated by Django 5.0.1 on 2024-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdiscount',
            name='seven_day_booking_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customdiscount',
            name='valid_cars',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
