# Generated by Django 5.0.1 on 2024-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_remove_customdiscount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdiscount',
            name='valid_cars',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
