# Generated by Django 5.0.1 on 2024-07-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_rename_custom_deposite_percentage_product_custom_deposite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pro_tips',
            new_name='why_choose_this',
        ),
    ]
